!!python/object:ml_collections.config_dict.config_dict.ConfigDict
_allow_dotted_keys: false
_convert_dict: true
_fields:
  data: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _allow_dotted_keys: false
    _convert_dict: true
    _fields:
      num_workers: 4
    _locked: true
    _sort_keys: true
    _type_safe: true
  eeg: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _allow_dotted_keys: false
    _convert_dict: true
    _fields:
      in_channels: 22
      num_classes: 5
    _locked: true
    _sort_keys: true
    _type_safe: true
  model: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _allow_dotted_keys: false
    _convert_dict: true
    _fields:
      architecture: CNN_BiLSTM
      checkpoint_name: CNN_BiLSTM_v1
      cnnbilstm: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
        _allow_dotted_keys: false
        _convert_dict: true
        _fields:
          dropout: 0.5
          hidden_dim: 64
          rnn_layers: 2
        _locked: true
        _sort_keys: true
        _type_safe: true
    _locked: true
    _sort_keys: true
    _type_safe: true
  preprocessing: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _allow_dotted_keys: false
    _convert_dict: true
    _fields:
      cache_path: ./moabb_cache
      freq_fork: !!python/tuple
      - 4
      - 40
      resample_rate: 250
      stft_nperseg: 64
      stft_overlap: 48
      t_fork: !!python/tuple
      - 0
      - 6
      use_cache: true
      window_overlap: 0.9
      window_sec: 3.0
    _locked: true
    _sort_keys: true
    _type_safe: true
  regularization: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _allow_dotted_keys: false
    _convert_dict: true
    _fields:
      channel_dropout: 0.1
      clip_sigma: 4.0
      gaussian_std: 0.05
      max_shift: 10
      scale_fork: !!python/tuple
      - 0.9
      - 1.1
    _locked: true
    _sort_keys: true
    _type_safe: true
  seed: 4269
  training: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _allow_dotted_keys: false
    _convert_dict: true
    _fields:
      batch_size: 32
      epochs: 1000
      es_min_delta: 0.0
      es_patience: 48
      gradient_clip_norm: 2.0
      loss_function: CrossEntropyLoss
      lr: 0.001
      lr_factor: 0.5
      lr_patience: 16
      min_lr: 1.0e-07
      optimizer: AdamW
      rollback_min_delta: 0.0
      rollback_on_disk: false
      rollback_patience: 16
      weight_decay: 0.01
    _locked: true
    _sort_keys: true
    _type_safe: true
_locked: true
_sort_keys: true
_type_safe: true
